### ISSUE TITLE
Poor Collada support - Doesn't support Z up axis

### ISSUE THREAD

**Issue by BennyKJohnson** [SonyWWS/LevelEditor#20]
Hi,

I've been experimenting with the LevelEditor, I want to work with mostly Collada model assets. However the geometry is based on the Z-axis being upwards. Despite this being indicated in the Collada file with  ''<up_axis>Z_UP</up_axis>" in the asset section, when imported models are orientated incorrectly.

I was wondering if it was possible to add support so the LevelEditor automatically accounts for a Z-UP axis and translates it to its own coordinate system.

As I'm relatively new to the code base I was hoping someone could point out where I should make adjustments and what adjustments should be made. 

![Screenshot of default orientation for a Z-up model](http://s13.postimg.org/5ct8c2lhj/viewport.png)

Thanks

**Comment by abeckus** [comment]
Hi Benjamin,
Thanks for reporting the issue.  I will add it to the task list.

LevelEditor parses Collada models using ColladaModelFactory.cpp located at:
.\LevelEditorNativeRendering\LvEdRenderingEngine\Model3d

This is the  entry function, it parses collada file starting from root element.
void ColladaModelFactory::ProcessXml(xml_node * rootXml, Model3dBuilder * builder)

I don't have any collada asset with z-up attribute, do you have any that you are willing to share.

Collada is very extensive file format, we don't provide full support so there could be other deficiencies.


Alan

**Comment by BennyKJohnson** [comment]
Hi,
Thanks Alan for your swift reply. The model I was testing can be found on [Turbo Squid](http://www.turbosquid.com/3d-models/male-character-3ds/525305). I apologise for the inconvenience as I can't offer you a direct link due to license restrictions otherwise I would.

I'll take a look at the code and see if I can add support myself. If I workout one I will post my solution for others to use until you can add official support.

Kind Regards,
Benjamin

**Comment by abeckus** [comment]
Fixed,
Collada importer applies a rotational transform to the root node to change it from z-up to y-up. 
Please let me know if you find any other issue or have a questions.

Alan

**Comment by bsteffel** [comment]
We export in Y up so this is a non issue. We no longer use Max.
