### ISSUE TITLE
DomGen.exe Dependency

### ISSUE THREAD

**Issue by devgoeson** [SonyWWS/LevelEditor#22]
Hi

I'm trying to add an own new GameObjectType according to LevelEditor-ProgrammigGuide.
Although It says "Run the GenSchemaDef.bat", that .bat file couldn't find DomGen.exe.
Because it points relative path "..\..\..\wws_atf\DevTools\DomGen\bin\DomGen.exe" which is out of LevelEditor repository. Then I need to checkout ATF separately and fix the path.

It's not that big problem though, it is helpful if LevelEditor repository includes DomGen.exe.

Thanks,
Shintaro Iguchi

**Comment by abeckus** [comment]
Thanks for reporting the issue.
I added DomGen.exe and fixed the relative path.

Alan

**Comment by devgoeson** [comment]
Hi Alan,

I've confirmed that works properly. This is quite helpful!
Thank you so much.

Shintaro Iguchi
