### ISSUE TITLE
Is there a limitation of up to 8 layers for the Terrain Editor?

### ISSUE THREAD

**Issue by secondwtq** [SonyWWS/LevelEditor#24]
I went through the code and found it in the rendering part. Adding the ninth layer just results a crash (not an exception), which I believes residing in the same module too.

If it's the case, I suggest it should be listed as a limitation (I did not found it in the wiki and documentation), and provide some message in the application notifying user not to add too many layers.

**Comment by abeckus** [comment]
Hi,
Thanks for reporting the issue.
Yes currently the max layer is set to eight layers but it can be changed by changing the following define:
#define MaxNumLayers 8    in TerrainShader.h

The docs and app should indicate the max number of layers.
We will consider making the changes in future releases.

Thanks
Alan

**Comment by secondwtq** [comment]
Gotcha, Thanks!
